version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"    # DNS
      - "53:53/udp"    # DNS
      - "80:80/tcp"    # Web interface
      - "443:443/tcp"  # Web interface (HTTPS)
    environment:
      - TZ=America/New_York  # Your timezone
      - WEBPASSWORD=your_secure_password  # Set your admin password here
    volumes:
      - ./etc-pihole:/etc/pihole  # Persistent Pi-hole config
      - ./etc-dnsmasq.d:/etc/dnsmasq.d  # Persistent DNS config
    cap_add:
      - NET_ADMIN  # Required for DNS functionality
    restart: unless-stopped
