FROM arm32v7/ubuntu:20.04
RUN apt-get update && apt-get install -y squid openssl bash
COPY squid.conf /etc/squid/squid.conf
COPY blocked_patterns.txt /etc/squid/blocked_patterns.txt
COPY entrypoint.sh /entrypoint.sh
COPY squid-ca.pem /etc/squid/squid-ca.pem
RUN chmod +x /entrypoint.sh && chown proxy:proxy /etc/squid/squid-ca.pem && chmod 600 /etc/squid/squid-ca.pem
