version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/London'
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    networks:
      - proxy_network

  squid:
    container_name: squid_proxy
    build:
      context: .
      dockerfile: Dockerfile.squid
    ports:
      - "3128:3128"
      - "3129:3129"
      - "3130:3130"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./blocked_patterns.txt:/etc/squid/blocked_patterns.txt
      - ./entrypoint.sh:/entrypoint.sh
      - ./squid-ca.pem:/etc/squid/squid-ca.pem
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    tty: true
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN
    network_mode: "host"
  restart: unless-stopped

networks:
  proxy_network:
    driver: bridge
