version: "3.8"

services:
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "80:80/tcp"
  #     - "443:443/tcp"
  #   environment:
  #     TZ: 'Europe/London'
  #     FTLCONF_webserver_api_password: 'correct horse battery staple'
  #     FTLCONF_dns_listeningMode: 'all'
  #   volumes:
  #     - './etc-pihole:/etc/pihole'
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_TIME
  #     - SYS_NICE
  #   restart: unless-stopped
  #   networks:
  #     - proxy_network

  squid:
    container_name: squid_proxy
    build:
      context: .
      dockerfile: Dockerfile.squid
    ports:
      - "3128:3128"
    volumes:
      - squid_cache:/var/spool/squid
      - ./squid.conf:/etc/squid/squid.conf
      - ./blocked_patterns.txt:/etc/squid/blocked_patterns.txt
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    tty: true  # Helps capture output
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge

volumes:
  squid_cache: